### PR TITLE
parsec: drop not used llvm dependency

### PR DESCRIPTION
**Pull request by muvarov**
drop not used llvm dependency

### CODE REVIEW

**Review by apalos — APPROVED** [review]

**Comment by muvarov** [comment]
Hm, with removing CI reports the following issue:
```
02:46:55 | /srv/oe/build-rpb/arm64-glibc/work/aarch64-linaro-linux/parsec/git-r0/recipe-sysroot-native/usr/bin/cmake: /srv/oe/build-rpb/arm64-glibc/work/aarch64-linaro-linux/parsec/git-r0/recipe-sysroot-native/usr/lib/libcurl.so.4: no version information available (required by /srv/oe/build-rpb/arm64-glibc/work/aarch64-linaro-linux/parsec/git-r0/recipe-sysroot-native/usr/bin/cmake)
02:46:55 | /usr/include/limits.h:124:16: fatal error: 'limits.h' file not found
02:46:55 | /usr/include/limits.h:124:16: fatal error: 'limits.h' file not found, err: true
02:46:55 | Error: Custom { kind: Other, error: "Unable to generate bindings to mbed crypto" }
02:46:55 | 
02:46:55 | WARNING: exit code 101 from a shell command.
02:46:55 | 
02:46:55 NOTE: recipe parsec-git-r0: task do_compile: Failed
02:46:55 ERROR: Task (mc:qemuarm64:/srv/oe/build-rpb/conf/../../layers/meta-ledge/meta-ledge-sw/recipes-security/parsec/parsec_git.bb:do_compile) failed with exit code '1'
```

**Comment by apalos** [comment]
> Hm, with removing CI reports the following issue:
> 
> ```
> 02:46:55 | /srv/oe/build-rpb/arm64-glibc/work/aarch64-linaro-linux/parsec/git-r0/recipe-sysroot-native/usr/bin/cmake: /srv/oe/build-rpb/arm64-glibc/work/aarch64-linaro-linux/parsec/git-r0/recipe-sysroot-native/usr/lib/libcurl.so.4: no version information available (required by /srv/oe/build-rpb/arm64-glibc/work/aarch64-linaro-linux/parsec/git-r0/recipe-sysroot-native/usr/bin/cmake)
> 02:46:55 | /usr/include/limits.h:124:16: fatal error: 'limits.h' file not found
> 02:46:55 | /usr/include/limits.h:124:16: fatal error: 'limits.h' file not found, err: true
> 02:46:55 | Error: Custom { kind: Other, error: "Unable to generate bindings to mbed crypto" }
> 02:46:55 | 
> 02:46:55 | WARNING: exit code 101 from a shell command.
> 02:46:55 | 
> 02:46:55 NOTE: recipe parsec-git-r0: task do_compile: Failed
> 02:46:55 ERROR: Task (mc:qemuarm64:/srv/oe/build-rpb/conf/../../layers/meta-ledge/meta-ledge-sw/recipes-security/parsec/parsec_git.bb:do_compile) failed with exit code '1'
> ```

So llv-native is needed? Does it have to be a package or can it just go into a DEPENDS .bb file?

**Comment by muvarov** [comment]
@apalos  on hb2 we have llvm in the host and this package is not needed. If you think that is better to use host one then I can update CI Dockerfile to add llvm. In that case we will save some time on compilation.

**Comment by muvarov** [comment]
Close

**Pull request closed without merging**
